/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityFaqRouteImport } from './routes/security-faq'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GetAppmapRouteImport } from './routes/get-appmap'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CliQuickstartRouteImport } from './routes/cli-quickstart'
import { Route as BookADemoRouteImport } from './routes/book-a-demo'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NavieSplatRouteImport } from './routes/navie.$'
import { Route as DocsNavieSplatRouteImport } from './routes/docs.navie.$'
import { Route as Blog20240620AppmapSweBenchLeaderRouteImport } from './routes/blog.2024.06.20.appmap-swe-bench-leader'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFaqRoute = SecurityFaqRouteImport.update({
  id: '/security-faq',
  path: '/security-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppmapRoute = GetAppmapRouteImport.update({
  id: '/get-appmap',
  path: '/get-appmap',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CliQuickstartRoute = CliQuickstartRouteImport.update({
  id: '/cli-quickstart',
  path: '/cli-quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookADemoRoute = BookADemoRouteImport.update({
  id: '/book-a-demo',
  path: '/book-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavieSplatRoute = NavieSplatRouteImport.update({
  id: '/navie/$',
  path: '/navie/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsNavieSplatRoute = DocsNavieSplatRouteImport.update({
  id: '/docs/navie/$',
  path: '/docs/navie/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog20240620AppmapSweBenchLeaderRoute =
  Blog20240620AppmapSweBenchLeaderRouteImport.update({
    id: '/blog/2024/06/20/appmap-swe-bench-leader',
    path: '/blog/2024/06/20/appmap-swe-bench-leader',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/navie/$': typeof NavieSplatRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
  '/blog/2024/06/20/appmap-swe-bench-leader': typeof Blog20240620AppmapSweBenchLeaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/navie/$': typeof NavieSplatRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
  '/blog/2024/06/20/appmap-swe-bench-leader': typeof Blog20240620AppmapSweBenchLeaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/navie/$': typeof NavieSplatRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
  '/blog/2024/06/20/appmap-swe-bench-leader': typeof Blog20240620AppmapSweBenchLeaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/security-faq'
    | '/sitemap.xml'
    | '/navie/$'
    | '/docs/navie/$'
    | '/blog/2024/06/20/appmap-swe-bench-leader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/security-faq'
    | '/sitemap.xml'
    | '/navie/$'
    | '/docs/navie/$'
    | '/blog/2024/06/20/appmap-swe-bench-leader'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/security-faq'
    | '/sitemap.xml'
    | '/navie/$'
    | '/docs/navie/$'
    | '/blog/2024/06/20/appmap-swe-bench-leader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BookADemoRoute: typeof BookADemoRoute
  CliQuickstartRoute: typeof CliQuickstartRoute
  CompatibilityRoute: typeof CompatibilityRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GetAppmapRoute: typeof GetAppmapRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlatformRoute: typeof PlatformRoute
  SecurityFaqRoute: typeof SecurityFaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NavieSplatRoute: typeof NavieSplatRoute
  DocsNavieSplatRoute: typeof DocsNavieSplatRoute
  Blog20240620AppmapSweBenchLeaderRoute: typeof Blog20240620AppmapSweBenchLeaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-faq': {
      id: '/security-faq'
      path: '/security-faq'
      fullPath: '/security-faq'
      preLoaderRoute: typeof SecurityFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-appmap': {
      id: '/get-appmap'
      path: '/get-appmap'
      fullPath: '/get-appmap'
      preLoaderRoute: typeof GetAppmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-quickstart': {
      id: '/cli-quickstart'
      path: '/cli-quickstart'
      fullPath: '/cli-quickstart'
      preLoaderRoute: typeof CliQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-demo': {
      id: '/book-a-demo'
      path: '/book-a-demo'
      fullPath: '/book-a-demo'
      preLoaderRoute: typeof BookADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navie/$': {
      id: '/navie/$'
      path: '/navie/$'
      fullPath: '/navie/$'
      preLoaderRoute: typeof NavieSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/navie/$': {
      id: '/docs/navie/$'
      path: '/docs/navie/$'
      fullPath: '/docs/navie/$'
      preLoaderRoute: typeof DocsNavieSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/2024/06/20/appmap-swe-bench-leader': {
      id: '/blog/2024/06/20/appmap-swe-bench-leader'
      path: '/blog/2024/06/20/appmap-swe-bench-leader'
      fullPath: '/blog/2024/06/20/appmap-swe-bench-leader'
      preLoaderRoute: typeof Blog20240620AppmapSweBenchLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BenchmarksRoute: BenchmarksRoute,
  BookADemoRoute: BookADemoRoute,
  CliQuickstartRoute: CliQuickstartRoute,
  CompatibilityRoute: CompatibilityRoute,
  EnterpriseRoute: EnterpriseRoute,
  GetAppmapRoute: GetAppmapRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlatformRoute: PlatformRoute,
  SecurityFaqRoute: SecurityFaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NavieSplatRoute: NavieSplatRoute,
  DocsNavieSplatRoute: DocsNavieSplatRoute,
  Blog20240620AppmapSweBenchLeaderRoute: Blog20240620AppmapSweBenchLeaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
