/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityFaqRouteImport } from './routes/security-faq'
import { Route as ReleaseNotesRouteImport } from './routes/release-notes'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GetAppmapRouteImport } from './routes/get-appmap'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CliQuickstartRouteImport } from './routes/cli-quickstart'
import { Route as BookADemoRouteImport } from './routes/book-a-demo'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as NavieSplatRouteImport } from './routes/navie.$'
import { Route as BlogGoldenAppmapTracesRuntimeContextRouteImport } from './routes/blog.golden-appmap-traces-runtime-context'
import { Route as DocsNavieSplatRouteImport } from './routes/docs.navie.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFaqRoute = SecurityFaqRouteImport.update({
  id: '/security-faq',
  path: '/security-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesRoute = ReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppmapRoute = GetAppmapRouteImport.update({
  id: '/get-appmap',
  path: '/get-appmap',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CliQuickstartRoute = CliQuickstartRouteImport.update({
  id: '/cli-quickstart',
  path: '/cli-quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookADemoRoute = BookADemoRouteImport.update({
  id: '/book-a-demo',
  path: '/book-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavieSplatRoute = NavieSplatRouteImport.update({
  id: '/navie/$',
  path: '/navie/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogGoldenAppmapTracesRuntimeContextRoute =
  BlogGoldenAppmapTracesRuntimeContextRouteImport.update({
    id: '/blog/golden-appmap-traces-runtime-context',
    path: '/blog/golden-appmap-traces-runtime-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsNavieSplatRoute = DocsNavieSplatRouteImport.update({
  id: '/docs/navie/$',
  path: '/docs/navie/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/golden-appmap-traces-runtime-context': typeof BlogGoldenAppmapTracesRuntimeContextRoute
  '/navie/$': typeof NavieSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/golden-appmap-traces-runtime-context': typeof BlogGoldenAppmapTracesRuntimeContextRoute
  '/navie/$': typeof NavieSplatRoute
  '/blog': typeof BlogIndexRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-a-demo': typeof BookADemoRoute
  '/cli-quickstart': typeof CliQuickstartRoute
  '/compatibility': typeof CompatibilityRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-appmap': typeof GetAppmapRoute
  '/how-it-works': typeof HowItWorksRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/security-faq': typeof SecurityFaqRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/golden-appmap-traces-runtime-context': typeof BlogGoldenAppmapTracesRuntimeContextRoute
  '/navie/$': typeof NavieSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/navie/$': typeof DocsNavieSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/pricing'
    | '/release-notes'
    | '/security-faq'
    | '/sitemap.xml'
    | '/blog/golden-appmap-traces-runtime-context'
    | '/navie/$'
    | '/blog/'
    | '/docs/navie/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/pricing'
    | '/release-notes'
    | '/security-faq'
    | '/sitemap.xml'
    | '/blog/golden-appmap-traces-runtime-context'
    | '/navie/$'
    | '/blog'
    | '/docs/navie/$'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/book-a-demo'
    | '/cli-quickstart'
    | '/compatibility'
    | '/enterprise'
    | '/get-appmap'
    | '/how-it-works'
    | '/platform'
    | '/pricing'
    | '/release-notes'
    | '/security-faq'
    | '/sitemap.xml'
    | '/blog/golden-appmap-traces-runtime-context'
    | '/navie/$'
    | '/blog/'
    | '/docs/navie/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BookADemoRoute: typeof BookADemoRoute
  CliQuickstartRoute: typeof CliQuickstartRoute
  CompatibilityRoute: typeof CompatibilityRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GetAppmapRoute: typeof GetAppmapRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ReleaseNotesRoute: typeof ReleaseNotesRoute
  SecurityFaqRoute: typeof SecurityFaqRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogGoldenAppmapTracesRuntimeContextRoute: typeof BlogGoldenAppmapTracesRuntimeContextRoute
  NavieSplatRoute: typeof NavieSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsNavieSplatRoute: typeof DocsNavieSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-faq': {
      id: '/security-faq'
      path: '/security-faq'
      fullPath: '/security-faq'
      preLoaderRoute: typeof SecurityFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes': {
      id: '/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof ReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-appmap': {
      id: '/get-appmap'
      path: '/get-appmap'
      fullPath: '/get-appmap'
      preLoaderRoute: typeof GetAppmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-quickstart': {
      id: '/cli-quickstart'
      path: '/cli-quickstart'
      fullPath: '/cli-quickstart'
      preLoaderRoute: typeof CliQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-demo': {
      id: '/book-a-demo'
      path: '/book-a-demo'
      fullPath: '/book-a-demo'
      preLoaderRoute: typeof BookADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navie/$': {
      id: '/navie/$'
      path: '/navie/$'
      fullPath: '/navie/$'
      preLoaderRoute: typeof NavieSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/golden-appmap-traces-runtime-context': {
      id: '/blog/golden-appmap-traces-runtime-context'
      path: '/blog/golden-appmap-traces-runtime-context'
      fullPath: '/blog/golden-appmap-traces-runtime-context'
      preLoaderRoute: typeof BlogGoldenAppmapTracesRuntimeContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/navie/$': {
      id: '/docs/navie/$'
      path: '/docs/navie/$'
      fullPath: '/docs/navie/$'
      preLoaderRoute: typeof DocsNavieSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BenchmarksRoute: BenchmarksRoute,
  BookADemoRoute: BookADemoRoute,
  CliQuickstartRoute: CliQuickstartRoute,
  CompatibilityRoute: CompatibilityRoute,
  EnterpriseRoute: EnterpriseRoute,
  GetAppmapRoute: GetAppmapRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ReleaseNotesRoute: ReleaseNotesRoute,
  SecurityFaqRoute: SecurityFaqRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogGoldenAppmapTracesRuntimeContextRoute:
    BlogGoldenAppmapTracesRuntimeContextRoute,
  NavieSplatRoute: NavieSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsNavieSplatRoute: DocsNavieSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
